version: '3.7'
services:
  postgre_sql_service:
    container_name: postgre_sql_service
    image: postgis/postgis:11-2.5
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DATABASE=clojure"
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - ./test_data/script/create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
      - ./test_data/script/sql_setup.sh:/docker-entrypoint-initdb.d/02-setup.sh
      - ./test_data/script/data_schema.sql.gz:/home/data_schema.sql.gz
      - ./test_data/files:/home/files
    ports:
      - '5432:5432'